### PR TITLE
fix overfetching of users in AssigmentList

### LINKED ISSUE #699: AssignmentList calls `fetchUser` too many times
As `fetchUser` is not currently encapsulated using `useEffect` in AssignmentList, it often issues far too many requests to the backend on loading the source page. 

image

### PR DESCRIPTION
**Pull request by dannygoldstein**
Fixes #699 .

The currently merged solution to this issue (#759 ) is flawed in that it provides a dependency list with a length that can change (spread syntax). This can cause React errors.

The solution here avoids the spread syntax and passes a fixed dependency list to `useEffect` each time the component is rerendered. A useState hook is used to prevent redundant `fetchUser` calls between renders.

### CODE REVIEW

File: static/js/components/AssignmentList.jsx [hunk 1]
```diff
@@ -15,20 +15,21 @@ const AssignmentList = ({ assignments }) => {
...
-  uniqueRequesterIDs.sort((a, b) => a - b);
 
   // use useEffect to only send 1 fetchUser per User
   useEffect(() => {
-    uniqueRequesterIDs.forEach((id) => {
-      if (!users[id]) {
+    requesterIDs.forEach((id) => {
+      if (!users[id] && !loadingUsers.includes(id)) {
         dispatch(UserActions.fetchUser(id));
+        loadingUsers.push(id);
```
Comment (acrellin) [inline static/js/components/AssignmentList.jsx:28]: I think modifying the state object directly is an anti-pattern; we should make a copy of `loadingUsers`, operate on that copy, and then pass it into `setLoadingUsers`

File: static/js/components/AssignmentList.jsx [hunk 2]
```diff
@@ -15,20 +15,21 @@ const AssignmentList = ({ assignments }) => {
   const { users } = useSelector((state) => state);
   const { observingRunList } = useSelector((state) => state.observingRuns);
   const { instrumentList } = useSelector((state) => state.instruments);
+  const [loadingUsers, setLoadingUsers] = useState([]);
```
Comment (acrellin) [inline static/js/components/AssignmentList.jsx:18]:
```suggestion
  const [loadingOrLoadedUsers, setLoadingOrLoadedUsers] = useState([]);
```
So that we know it's not just for in-progress queries

File: static/js/components/AssignmentList.jsx [hunk 3]
```diff
@@ -15,20 +15,21 @@ const AssignmentList = ({ assignments }) => {
...
-      if (!users[id]) {
+    requesterIDs.forEach((id) => {
+      if (!users[id] && !loadingUsers.includes(id)) {
         dispatch(UserActions.fetchUser(id));
+        loadingUsers.push(id);
+        setLoadingUsers(loadingUsers);
       }
     });
-  }, [...uniqueRequesterIDs, users, dispatch]);
+  }, [requesterIDs, users, dispatch]);
```
Comment (acrellin) [inline static/js/components/AssignmentList.jsx:32]: Should `loadingUsers` be in the deps array here?

**Comment by dannygoldstein** [comment]
@acrellin opted for a different approach that does not use `useState`

**Review by acrellin — APPROVED** [review]
Nice
